name = "referrals-live"
compatibility_date = "2024-11-01"
pages_build_output_dir = "dist"

[vars]
APP_ORIGIN = "https://referrals.live"
SESSION_DAYS = "30"
OWNER_ADMIN_EMAIL = "mr.jwswain@gmail.com"

[[d1_databases]]
binding = "DB"
database_name = "referrals-live"
database_id = "8c825251-cdbf-4087-82a6-eebff2bbb176"
